Repository MicrosoftDocs/data-integration, pull requests merged in 2022-12, with the labels that each got.

#193 Repo sync for protected CLA branch
  data-integration/gateway/service-gateway-monthly-updates.md
Labels: on-premises-data-gateway/prod, CLA, do-not-merge, Change sent to author

#194 Repo sync for protected CLA branch
  data-integration/gateway/plan-scale-maintain.md
  data-integration/gateway/service-gateway-app.md
  data-integration/gateway/service-gateway-azure-relay.md
  data-integration/gateway/service-gateway-communication.md
  data-integration/gateway/service-gateway-configure-disk-space.md
  data-integration/gateway/service-gateway-data-region.md
  data-integration/gateway/service-gateway-high-availability-clusters.md
  data-integration/gateway/service-gateway-install.md
  data-integration/gateway/service-gateway-log-files.md
  data-integration/gateway/service-gateway-manage.md
  data-integration/gateway/service-gateway-migrate.md
  data-integration/gateway/service-gateway-onprem-faq.yml
  data-integration/gateway/service-gateway-onprem-indepth.md
  data-integration/gateway/service-gateway-onprem.md
  data-integration/gateway/service-gateway-performance-cpu.md
  data-integration/gateway/service-gateway-performance.md
  data-integration/gateway/service-gateway-powershell-support.md
  data-integration/gateway/service-gateway-proxy-setup-guide.md
  data-integration/gateway/service-gateway-proxy.md
  data-integration/gateway/service-gateway-recovery-key.md
  data-integration/gateway/service-gateway-restart.md
  data-integration/gateway/service-gateway-service-account.md
  data-integration/gateway/service-gateway-tshoot.md
  data-integration/gateway/service-gateway-update.md
  data-integration/includes/footer-banner.md
  data-integration/includes/gateway-rewrite.md
  data-integration/vnet/create-data-gateways.md
  data-integration/vnet/data-gateway-architecture.md
  data-integration/vnet/data-gateway-faqs.yml
  data-integration/vnet/data-gateway-power-platform-dataflows.md
  data-integration/vnet/manage-data-gateways.md
  data-integration/vnet/manage-vnet-security-roles.md
  data-integration/vnet/overview.md
  data-integration/vnet/sql-server-and-custom-connectors.md
  data-integration/vnet/troubleshoot-data-gateway.md
  data-integration/vnet/use-data-gateways-sources-power-bi.md
Labels: CLA, do-not-merge

#196 Repo sync for protected CLA branch
  data-integration/gateway/media/service-gateway-onprem-indepth/on-prem-data-gateway-how-it-works.png
Labels: CLA, do-not-merge, review-team-triage

#197 Repo sync for protected CLA branch
  data-integration/gateway/service-gateway-app.md
  data-integration/gateway/service-gateway-communication.md
  data-integration/gateway/service-gateway-onprem-faq.yml
  data-integration/gateway/service-gateway-onprem-indepth.md
  data-integration/gateway/service-gateway-tshoot.md
  data-integration/vnet/data-gateway-faqs.yml
Labels: CLA, do-not-merge

#198 Repo sync for protected CLA branch
  data-integration/vnet/overview.md
Labels: CLA, virtual-network-data-gateway/svc, do-not-merge, Change sent to author
