Repository MicrosoftDocs/data-integration, pull requests merged in 2023-01, with the labels that each got.

#201 Repo sync for protected CLA branch
  data-integration/gateway/service-gateway-install.md
  data-integration/gateway/service-gateway-performance.md
Labels: CLA, do-not-merge

#203 Repo sync for protected CLA branch
  data-integration/gateway/service-gateway-communication.md
  data-integration/gateway/service-gateway-onprem.md
Labels: CLA, do-not-merge, Change sent to author

#204 Repo sync for protected CLA branch
  data-integration/gateway/service-gateway-onprem.md
Labels: CLA, do-not-merge

#195 add detail on private link causing gateway configuration failure
  data-integration/gateway/service-gateway-install.md
Labels: on-premises-data-gateway/prod, do-not-merge, Change sent to author, qualifies-for-auto-merge
